/*
 * Binance Margin Trading API
 *
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::margin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginGetMarginBorrowRepayV1Resp {
    #[serde(rename = "rows", skip_serializing_if = "Option::is_none")]
    pub rows: Option<Vec<models::MarginGetMarginBorrowRepayV1RespRowsInner>>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl MarginGetMarginBorrowRepayV1Resp {
    pub fn new() -> MarginGetMarginBorrowRepayV1Resp {
        MarginGetMarginBorrowRepayV1Resp {
            rows: None,
            total: None,
        }
    }
}

