/*
 * Binance Margin Trading API
 *
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::margin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginGetMarginAvailableInventoryV1Resp {
    #[serde(rename = "assets", skip_serializing_if = "Option::is_none")]
    pub assets: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "updateTime", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<i64>,
}

impl MarginGetMarginAvailableInventoryV1Resp {
    pub fn new() -> MarginGetMarginAvailableInventoryV1Resp {
        MarginGetMarginAvailableInventoryV1Resp {
            assets: None,
            update_time: None,
        }
    }
}

