/*
 * Binance Margin Trading API
 *
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::margin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginGetMarginCrossMarginCollateralRatioV1RespItemCollateralsInner {
    #[serde(rename = "discountRate", skip_serializing_if = "Option::is_none")]
    pub discount_rate: Option<String>,
    #[serde(rename = "maxUsdValue", skip_serializing_if = "Option::is_none")]
    pub max_usd_value: Option<String>,
    #[serde(rename = "minUsdValue", skip_serializing_if = "Option::is_none")]
    pub min_usd_value: Option<String>,
}

impl MarginGetMarginCrossMarginCollateralRatioV1RespItemCollateralsInner {
    pub fn new() -> MarginGetMarginCrossMarginCollateralRatioV1RespItemCollateralsInner {
        MarginGetMarginCrossMarginCollateralRatioV1RespItemCollateralsInner {
            discount_rate: None,
            max_usd_value: None,
            min_usd_value: None,
        }
    }
}

