/*
 * Binance Margin Trading API
 *
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::margin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginGetMarginCrossMarginCollateralRatioV1RespItem {
    #[serde(rename = "assetNames", skip_serializing_if = "Option::is_none")]
    pub asset_names: Option<Vec<String>>,
    #[serde(rename = "collaterals", skip_serializing_if = "Option::is_none")]
    pub collaterals: Option<Vec<models::MarginGetMarginCrossMarginCollateralRatioV1RespItemCollateralsInner>>,
}

impl MarginGetMarginCrossMarginCollateralRatioV1RespItem {
    pub fn new() -> MarginGetMarginCrossMarginCollateralRatioV1RespItem {
        MarginGetMarginCrossMarginCollateralRatioV1RespItem {
            asset_names: None,
            collaterals: None,
        }
    }
}

