/*
 * Binance Margin Trading API
 *
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::margin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginGetMarginTransferV1RespRowsInner {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(rename = "transFrom", skip_serializing_if = "Option::is_none")]
    pub trans_from: Option<String>,
    #[serde(rename = "transTo", skip_serializing_if = "Option::is_none")]
    pub trans_to: Option<String>,
    #[serde(rename = "txId", skip_serializing_if = "Option::is_none")]
    pub tx_id: Option<i64>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl MarginGetMarginTransferV1RespRowsInner {
    pub fn new() -> MarginGetMarginTransferV1RespRowsInner {
        MarginGetMarginTransferV1RespRowsInner {
            amount: None,
            asset: None,
            status: None,
            timestamp: None,
            trans_from: None,
            trans_to: None,
            tx_id: None,
            r#type: None,
        }
    }
}

