/*
 * Binance Margin Trading API
 *
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::margin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginGetMarginAccountV1RespUserAssetsInner {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "borrowed", skip_serializing_if = "Option::is_none")]
    pub borrowed: Option<String>,
    #[serde(rename = "free", skip_serializing_if = "Option::is_none")]
    pub free: Option<String>,
    #[serde(rename = "interest", skip_serializing_if = "Option::is_none")]
    pub interest: Option<String>,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<String>,
    #[serde(rename = "netAsset", skip_serializing_if = "Option::is_none")]
    pub net_asset: Option<String>,
}

impl MarginGetMarginAccountV1RespUserAssetsInner {
    pub fn new() -> MarginGetMarginAccountV1RespUserAssetsInner {
        MarginGetMarginAccountV1RespUserAssetsInner {
            asset: None,
            borrowed: None,
            free: None,
            interest: None,
            locked: None,
            net_asset: None,
        }
    }
}

