/*
 * Binance Margin Trading API
 *
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::margin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginGetMarginNextHourlyInterestRateV1RespItem {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "nextHourlyInterestRate", skip_serializing_if = "Option::is_none")]
    pub next_hourly_interest_rate: Option<String>,
}

impl MarginGetMarginNextHourlyInterestRateV1RespItem {
    pub fn new() -> MarginGetMarginNextHourlyInterestRateV1RespItem {
        MarginGetMarginNextHourlyInterestRateV1RespItem {
            asset: None,
            next_hourly_interest_rate: None,
        }
    }
}

