/*
 * Binance Margin Trading API
 *
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::margin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginGetMarginIsolatedMarginDataV1RespItem {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::MarginGetMarginIsolatedMarginDataV1RespItemDataInner>>,
    #[serde(rename = "leverage", skip_serializing_if = "Option::is_none")]
    pub leverage: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "vipLevel", skip_serializing_if = "Option::is_none")]
    pub vip_level: Option<i32>,
}

impl MarginGetMarginIsolatedMarginDataV1RespItem {
    pub fn new() -> MarginGetMarginIsolatedMarginDataV1RespItem {
        MarginGetMarginIsolatedMarginDataV1RespItem {
            data: None,
            leverage: None,
            symbol: None,
            vip_level: None,
        }
    }
}

