/*
 * Binance Margin Trading API
 *
 * OpenAPI specification for Binance exchange - Margin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::margin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginCreateMarginExchangeSmallLiabilityV1Resp {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
}

impl MarginCreateMarginExchangeSmallLiabilityV1Resp {
    pub fn new() -> MarginCreateMarginExchangeSmallLiabilityV1Resp {
        MarginCreateMarginExchangeSmallLiabilityV1Resp {
            code: None,
            msg: None,
        }
    }
}

