/*
 * Binance Portfolio Margin API
 *
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::pmargin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMarginMaxBorrowableV1Resp {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    #[serde(rename = "borrowLimit", skip_serializing_if = "Option::is_none")]
    pub borrow_limit: Option<i32>,
}

impl GetMarginMaxBorrowableV1Resp {
    pub fn new() -> GetMarginMaxBorrowableV1Resp {
        GetMarginMaxBorrowableV1Resp {
            amount: None,
            borrow_limit: None,
        }
    }
}

