/*
 * Binance Portfolio Margin API
 *
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::pmargin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUmLeverageBracketV1RespItemBracketsInner {
    #[serde(rename = "bracket", skip_serializing_if = "Option::is_none")]
    pub bracket: Option<i32>,
    #[serde(rename = "cum", skip_serializing_if = "Option::is_none")]
    pub cum: Option<i32>,
    #[serde(rename = "initialLeverage", skip_serializing_if = "Option::is_none")]
    pub initial_leverage: Option<i32>,
    #[serde(rename = "maintMarginRatio", skip_serializing_if = "Option::is_none")]
    pub maint_margin_ratio: Option<f64>,
    #[serde(rename = "notionalCap", skip_serializing_if = "Option::is_none")]
    pub notional_cap: Option<i32>,
    #[serde(rename = "notionalFloor", skip_serializing_if = "Option::is_none")]
    pub notional_floor: Option<i32>,
}

impl GetUmLeverageBracketV1RespItemBracketsInner {
    pub fn new() -> GetUmLeverageBracketV1RespItemBracketsInner {
        GetUmLeverageBracketV1RespItemBracketsInner {
            bracket: None,
            cum: None,
            initial_leverage: None,
            maint_margin_ratio: None,
            notional_cap: None,
            notional_floor: None,
        }
    }
}

