/*
 * Binance Portfolio Margin API
 *
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::pmargin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInnerDetailsInner {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "negativeBalance", skip_serializing_if = "Option::is_none")]
    pub negative_balance: Option<i32>,
    #[serde(rename = "negativeMaxThreshold", skip_serializing_if = "Option::is_none")]
    pub negative_max_threshold: Option<i32>,
}

impl GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInnerDetailsInner {
    pub fn new() -> GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInnerDetailsInner {
        GetPortfolioNegativeBalanceExchangeRecordV1RespRowsInnerDetailsInner {
            asset: None,
            negative_balance: None,
            negative_max_threshold: None,
        }
    }
}

