/*
 * Binance Portfolio Margin API
 *
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::pmargin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCmLeverageBracketV1RespItemBracketsInner {
    #[serde(rename = "bracket", skip_serializing_if = "Option::is_none")]
    pub bracket: Option<i32>,
    #[serde(rename = "cum", skip_serializing_if = "Option::is_none")]
    pub cum: Option<i32>,
    #[serde(rename = "initialLeverage", skip_serializing_if = "Option::is_none")]
    pub initial_leverage: Option<i32>,
    #[serde(rename = "maintMarginRatio", skip_serializing_if = "Option::is_none")]
    pub maint_margin_ratio: Option<f64>,
    #[serde(rename = "qtyCap", skip_serializing_if = "Option::is_none")]
    pub qty_cap: Option<i32>,
    #[serde(rename = "qtyFloor", skip_serializing_if = "Option::is_none")]
    pub qty_floor: Option<i32>,
}

impl GetCmLeverageBracketV1RespItemBracketsInner {
    pub fn new() -> GetCmLeverageBracketV1RespItemBracketsInner {
        GetCmLeverageBracketV1RespItemBracketsInner {
            bracket: None,
            cum: None,
            initial_leverage: None,
            maint_margin_ratio: None,
            qty_cap: None,
            qty_floor: None,
        }
    }
}

