/*
 * Binance USD-M Futures API
 *
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::umfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccountV3RespAssetsInner {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "availableBalance", skip_serializing_if = "Option::is_none")]
    pub available_balance: Option<String>,
    #[serde(rename = "crossUnPnl", skip_serializing_if = "Option::is_none")]
    pub cross_un_pnl: Option<String>,
    #[serde(rename = "crossWalletBalance", skip_serializing_if = "Option::is_none")]
    pub cross_wallet_balance: Option<String>,
    #[serde(rename = "initialMargin", skip_serializing_if = "Option::is_none")]
    pub initial_margin: Option<String>,
    #[serde(rename = "maintMargin", skip_serializing_if = "Option::is_none")]
    pub maint_margin: Option<String>,
    #[serde(rename = "marginBalance", skip_serializing_if = "Option::is_none")]
    pub margin_balance: Option<String>,
    #[serde(rename = "maxWithdrawAmount", skip_serializing_if = "Option::is_none")]
    pub max_withdraw_amount: Option<String>,
    #[serde(rename = "openOrderInitialMargin", skip_serializing_if = "Option::is_none")]
    pub open_order_initial_margin: Option<String>,
    #[serde(rename = "positionInitialMargin", skip_serializing_if = "Option::is_none")]
    pub position_initial_margin: Option<String>,
    #[serde(rename = "unrealizedProfit", skip_serializing_if = "Option::is_none")]
    pub unrealized_profit: Option<String>,
    #[serde(rename = "updateTime", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<i64>,
    #[serde(rename = "walletBalance", skip_serializing_if = "Option::is_none")]
    pub wallet_balance: Option<String>,
}

impl GetAccountV3RespAssetsInner {
    pub fn new() -> GetAccountV3RespAssetsInner {
        GetAccountV3RespAssetsInner {
            asset: None,
            available_balance: None,
            cross_un_pnl: None,
            cross_wallet_balance: None,
            initial_margin: None,
            maint_margin: None,
            margin_balance: None,
            max_withdraw_amount: None,
            open_order_initial_margin: None,
            position_initial_margin: None,
            unrealized_profit: None,
            update_time: None,
            wallet_balance: None,
        }
    }
}

