/*
 * Binance USD-M Futures API
 *
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::umfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApiReferralRebateVolV1RespItem {
    #[serde(rename = "rebateVol", skip_serializing_if = "Option::is_none")]
    pub rebate_vol: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl GetApiReferralRebateVolV1RespItem {
    pub fn new() -> GetApiReferralRebateVolV1RespItem {
        GetApiReferralRebateVolV1RespItem {
            rebate_vol: None,
            time: None,
            unit: None,
        }
    }
}

