/*
 * Binance USD-M Futures API
 *
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::umfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApiReferralTraderSummaryV1RespItem {
    #[serde(rename = "customerId", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
    #[serde(rename = "rebateVol", skip_serializing_if = "Option::is_none")]
    pub rebate_vol: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
    #[serde(rename = "tradeVol", skip_serializing_if = "Option::is_none")]
    pub trade_vol: Option<String>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl GetApiReferralTraderSummaryV1RespItem {
    pub fn new() -> GetApiReferralTraderSummaryV1RespItem {
        GetApiReferralTraderSummaryV1RespItem {
            customer_id: None,
            rebate_vol: None,
            time: None,
            trade_vol: None,
            unit: None,
        }
    }
}

