/*
 * Binance USD-M Futures API
 *
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::umfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTradeAsynIdV1Resp {
    #[serde(rename = "downloadId", skip_serializing_if = "Option::is_none")]
    pub download_id: Option<String>,
    #[serde(rename = "expirationTimestamp", skip_serializing_if = "Option::is_none")]
    pub expiration_timestamp: Option<i64>,
    #[serde(rename = "isExpired", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_expired: Option<Option<serde_json::Value>>,
    #[serde(rename = "notified", skip_serializing_if = "Option::is_none")]
    pub notified: Option<bool>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl GetTradeAsynIdV1Resp {
    pub fn new() -> GetTradeAsynIdV1Resp {
        GetTradeAsynIdV1Resp {
            download_id: None,
            expiration_timestamp: None,
            is_expired: None,
            notified: None,
            status: None,
            url: None,
        }
    }
}

