/*
 * Binance USD-M Futures API
 *
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::umfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPmAccountInfoV1Resp {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "maxWithdrawAmount", skip_serializing_if = "Option::is_none")]
    pub max_withdraw_amount: Option<String>,
    #[serde(rename = "maxWithdrawAmountUSD", skip_serializing_if = "Option::is_none")]
    pub max_withdraw_amount_usd: Option<String>,
}

impl GetPmAccountInfoV1Resp {
    pub fn new() -> GetPmAccountInfoV1Resp {
        GetPmAccountInfoV1Resp {
            asset: None,
            max_withdraw_amount: None,
            max_withdraw_amount_usd: None,
        }
    }
}

