/*
 * Binance USD-M Futures API
 *
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::umfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UmfuturesDeleteBatchOrdersV1RespInner {
    UmfuturesDeleteBatchOrdersV1RespItem(Box<models::UmfuturesDeleteBatchOrdersV1RespItem>),
    ApiError(Box<models::ApiError>),
}

impl Default for UmfuturesDeleteBatchOrdersV1RespInner {
    fn default() -> Self {
        Self::UmfuturesDeleteBatchOrdersV1RespItem(Default::default())
    }
}

