/*
 * Binance USD-M Futures API
 *
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::umfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UmfuturesGetExchangeInfoV1RespSymbolsInner {
    #[serde(rename = "OrderType", skip_serializing_if = "Option::is_none")]
    pub order_type: Option<Vec<String>>,
    #[serde(rename = "baseAsset", skip_serializing_if = "Option::is_none")]
    pub base_asset: Option<String>,
    #[serde(rename = "baseAssetPrecision", skip_serializing_if = "Option::is_none")]
    pub base_asset_precision: Option<i32>,
    #[serde(rename = "contractType", skip_serializing_if = "Option::is_none")]
    pub contract_type: Option<String>,
    #[serde(rename = "deliveryDate", skip_serializing_if = "Option::is_none")]
    pub delivery_date: Option<i32>,
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<models::UmfuturesGetExchangeInfoV1RespSymbolsInnerFiltersInner>>,
    #[serde(rename = "liquidationFee", skip_serializing_if = "Option::is_none")]
    pub liquidation_fee: Option<String>,
    #[serde(rename = "maintMarginPercent", skip_serializing_if = "Option::is_none")]
    pub maint_margin_percent: Option<String>,
    #[serde(rename = "marginAsset", skip_serializing_if = "Option::is_none")]
    pub margin_asset: Option<String>,
    #[serde(rename = "marketTakeBound", skip_serializing_if = "Option::is_none")]
    pub market_take_bound: Option<String>,
    #[serde(rename = "onboardDate", skip_serializing_if = "Option::is_none")]
    pub onboard_date: Option<i32>,
    #[serde(rename = "pair", skip_serializing_if = "Option::is_none")]
    pub pair: Option<String>,
    #[serde(rename = "pricePrecision", skip_serializing_if = "Option::is_none")]
    pub price_precision: Option<i32>,
    #[serde(rename = "quantityPrecision", skip_serializing_if = "Option::is_none")]
    pub quantity_precision: Option<i32>,
    #[serde(rename = "quoteAsset", skip_serializing_if = "Option::is_none")]
    pub quote_asset: Option<String>,
    #[serde(rename = "quotePrecision", skip_serializing_if = "Option::is_none")]
    pub quote_precision: Option<i32>,
    #[serde(rename = "requiredMarginPercent", skip_serializing_if = "Option::is_none")]
    pub required_margin_percent: Option<String>,
    #[serde(rename = "settlePlan", skip_serializing_if = "Option::is_none")]
    pub settle_plan: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "timeInForce", skip_serializing_if = "Option::is_none")]
    pub time_in_force: Option<Vec<String>>,
    #[serde(rename = "triggerProtect", skip_serializing_if = "Option::is_none")]
    pub trigger_protect: Option<String>,
    #[serde(rename = "underlyingSubType", skip_serializing_if = "Option::is_none")]
    pub underlying_sub_type: Option<Vec<String>>,
    #[serde(rename = "underlyingType", skip_serializing_if = "Option::is_none")]
    pub underlying_type: Option<String>,
}

impl UmfuturesGetExchangeInfoV1RespSymbolsInner {
    pub fn new() -> UmfuturesGetExchangeInfoV1RespSymbolsInner {
        UmfuturesGetExchangeInfoV1RespSymbolsInner {
            order_type: None,
            base_asset: None,
            base_asset_precision: None,
            contract_type: None,
            delivery_date: None,
            filters: None,
            liquidation_fee: None,
            maint_margin_percent: None,
            margin_asset: None,
            market_take_bound: None,
            onboard_date: None,
            pair: None,
            price_precision: None,
            quantity_precision: None,
            quote_asset: None,
            quote_precision: None,
            required_margin_percent: None,
            settle_plan: None,
            status: None,
            symbol: None,
            time_in_force: None,
            trigger_protect: None,
            underlying_sub_type: None,
            underlying_type: None,
        }
    }
}

