/*
 * Binance USD-M Futures API
 *
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::umfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UmfuturesGetPremiumIndexV1Resp {
    Array(Vec<models::UmfuturesGetPremiumIndexV1RespItem>),
    UmfuturesGetPremiumIndexV1RespItem(Box<models::UmfuturesGetPremiumIndexV1RespItem>),
}

impl Default for UmfuturesGetPremiumIndexV1Resp {
    fn default() -> Self {
        Self::Array(Default::default())
    }
}

