/*
 * Binance USD-M Futures API
 *
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::umfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UmfuturesGetOrderAsynV1Resp {
    #[serde(rename = "avgCostTimestampOfLast30d", skip_serializing_if = "Option::is_none")]
    pub avg_cost_timestamp_of_last30d: Option<i64>,
    #[serde(rename = "downloadId", skip_serializing_if = "Option::is_none")]
    pub download_id: Option<String>,
}

impl UmfuturesGetOrderAsynV1Resp {
    pub fn new() -> UmfuturesGetOrderAsynV1Resp {
        UmfuturesGetOrderAsynV1Resp {
            avg_cost_timestamp_of_last30d: None,
            download_id: None,
        }
    }
}

