/*
 * Binance Portfolio Margin Pro API
 *
 * OpenAPI specification for Binance exchange - Pmarginpro API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::pmarginpro::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PmarginproCreatePortfolioRepayV1Resp {
    #[serde(rename = "tranId", skip_serializing_if = "Option::is_none")]
    pub tran_id: Option<i64>,
}

impl PmarginproCreatePortfolioRepayV1Resp {
    pub fn new() -> PmarginproCreatePortfolioRepayV1Resp {
        PmarginproCreatePortfolioRepayV1Resp {
            tran_id: None,
        }
    }
}

