/*
 * Binance USD-M Futures API
 *
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::umfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UmfuturesCreateMultiAssetsMarginV1Resp {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
}

impl UmfuturesCreateMultiAssetsMarginV1Resp {
    pub fn new() -> UmfuturesCreateMultiAssetsMarginV1Resp {
        UmfuturesCreateMultiAssetsMarginV1Resp {
            code: None,
            msg: None,
        }
    }
}

