/*
 * Binance USD-M Futures API
 *
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::umfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UmfuturesCreateConvertAcceptQuoteV1Resp {
    #[serde(rename = "createTime", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<i64>,
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
    #[serde(rename = "orderStatus", skip_serializing_if = "Option::is_none")]
    pub order_status: Option<String>,
}

impl UmfuturesCreateConvertAcceptQuoteV1Resp {
    pub fn new() -> UmfuturesCreateConvertAcceptQuoteV1Resp {
        UmfuturesCreateConvertAcceptQuoteV1Resp {
            create_time: None,
            order_id: None,
            order_status: None,
        }
    }
}

