/*
 * Binance USD-M Futures API
 *
 * OpenAPI specification for Binance exchange - Umfutures API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::umfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UmfuturesGetCommissionRateV1Resp {
    #[serde(rename = "makerCommissionRate", skip_serializing_if = "Option::is_none")]
    pub maker_commission_rate: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "takerCommissionRate", skip_serializing_if = "Option::is_none")]
    pub taker_commission_rate: Option<String>,
}

impl UmfuturesGetCommissionRateV1Resp {
    pub fn new() -> UmfuturesGetCommissionRateV1Resp {
        UmfuturesGetCommissionRateV1Resp {
            maker_commission_rate: None,
            symbol: None,
            taker_commission_rate: None,
        }
    }
}

