/*
 * Binance Options API
 *
 * OpenAPI specification for Binance exchange - Options API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::options::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCountdownCancelAllV1Resp {
    #[serde(rename = "countdownTime", skip_serializing_if = "Option::is_none")]
    pub countdown_time: Option<i64>,
    #[serde(rename = "underlying", skip_serializing_if = "Option::is_none")]
    pub underlying: Option<String>,
}

impl CreateCountdownCancelAllV1Resp {
    pub fn new() -> CreateCountdownCancelAllV1Resp {
        CreateCountdownCancelAllV1Resp {
            countdown_time: None,
            underlying: None,
        }
    }
}

