/*
 * Binance Options API
 *
 * OpenAPI specification for Binance exchange - Options API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::options::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OptionsDeleteBatchOrdersV1RespInner {
    OptionsDeleteBatchOrdersV1RespItem(Box<models::OptionsDeleteBatchOrdersV1RespItem>),
    ApiError(Box<models::ApiError>),
}

impl Default for OptionsDeleteBatchOrdersV1RespInner {
    fn default() -> Self {
        Self::OptionsDeleteBatchOrdersV1RespItem(Default::default())
    }
}

