/*
 * Binance Sub Account API
 *
 * OpenAPI specification for Binance exchange - Subaccount API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::subaccount::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubaccountGetSubAccountFuturesAccountV2Resp {
    #[serde(rename = "futureAccountResp", skip_serializing_if = "Option::is_none")]
    pub future_account_resp: Option<Box<models::SubaccountGetSubAccountFuturesAccountV2RespFutureAccountResp>>,
}

impl SubaccountGetSubAccountFuturesAccountV2Resp {
    pub fn new() -> SubaccountGetSubAccountFuturesAccountV2Resp {
        SubaccountGetSubAccountFuturesAccountV2Resp {
            future_account_resp: None,
        }
    }
}

