/*
 * Binance Sub Account API
 *
 * OpenAPI specification for Binance exchange - Subaccount API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::subaccount::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubaccountCreateSubAccountBlvtEnableV1Resp {
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "enableBlvt", skip_serializing_if = "Option::is_none")]
    pub enable_blvt: Option<bool>,
}

impl SubaccountCreateSubAccountBlvtEnableV1Resp {
    pub fn new() -> SubaccountCreateSubAccountBlvtEnableV1Resp {
        SubaccountCreateSubAccountBlvtEnableV1Resp {
            email: None,
            enable_blvt: None,
        }
    }
}

