/*
 * Binance Sub Account API
 *
 * OpenAPI specification for Binance exchange - Subaccount API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::subaccount::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubaccountGetManagedSubaccountFetchFutureAssetV1Resp {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "snapshotVos", skip_serializing_if = "Option::is_none")]
    pub snapshot_vos: Option<Vec<models::SubaccountGetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInner>>,
}

impl SubaccountGetManagedSubaccountFetchFutureAssetV1Resp {
    pub fn new() -> SubaccountGetManagedSubaccountFetchFutureAssetV1Resp {
        SubaccountGetManagedSubaccountFetchFutureAssetV1Resp {
            code: None,
            message: None,
            snapshot_vos: None,
        }
    }
}

