/*
 * Binance Sub Account API
 *
 * OpenAPI specification for Binance exchange - Subaccount API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::subaccount::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner {
    #[serde(rename = "bindParentEmail", skip_serializing_if = "Option::is_none")]
    pub bind_parent_email: Option<String>,
    #[serde(rename = "bindParentUserId", skip_serializing_if = "Option::is_none")]
    pub bind_parent_user_id: Option<i64>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "insertTimeStamp", skip_serializing_if = "Option::is_none")]
    pub insert_time_stamp: Option<i32>,
    #[serde(rename = "isFutureEnabled", skip_serializing_if = "Option::is_none")]
    pub is_future_enabled: Option<bool>,
    #[serde(rename = "isMarginEnabled", skip_serializing_if = "Option::is_none")]
    pub is_margin_enabled: Option<bool>,
    #[serde(rename = "isSignedLVTRiskAgreement", skip_serializing_if = "Option::is_none")]
    pub is_signed_lvt_risk_agreement: Option<bool>,
    #[serde(rename = "isSubUserEnabled", skip_serializing_if = "Option::is_none")]
    pub is_sub_user_enabled: Option<bool>,
    #[serde(rename = "isUserActive", skip_serializing_if = "Option::is_none")]
    pub is_user_active: Option<bool>,
    #[serde(rename = "managersubUserId", skip_serializing_if = "Option::is_none")]
    pub managersub_user_id: Option<i64>,
    #[serde(rename = "rootUserId", skip_serializing_if = "Option::is_none")]
    pub root_user_id: Option<i64>,
}

impl SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner {
    pub fn new() -> SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner {
        SubaccountGetManagedSubaccountInfoV1RespManagerSubUserInfoVoListInner {
            bind_parent_email: None,
            bind_parent_user_id: None,
            email: None,
            insert_time_stamp: None,
            is_future_enabled: None,
            is_margin_enabled: None,
            is_signed_lvt_risk_agreement: None,
            is_sub_user_enabled: None,
            is_user_active: None,
            managersub_user_id: None,
            root_user_id: None,
        }
    }
}

