/*
 * Binance Sub Account API
 *
 * OpenAPI specification for Binance exchange - Subaccount API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::subaccount::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubaccountGetManagedSubaccountAccountSnapshotV1RespSnapshotVosInnerDataBalancesInner {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "free", skip_serializing_if = "Option::is_none")]
    pub free: Option<String>,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<String>,
}

impl SubaccountGetManagedSubaccountAccountSnapshotV1RespSnapshotVosInnerDataBalancesInner {
    pub fn new() -> SubaccountGetManagedSubaccountAccountSnapshotV1RespSnapshotVosInnerDataBalancesInner {
        SubaccountGetManagedSubaccountAccountSnapshotV1RespSnapshotVosInnerDataBalancesInner {
            asset: None,
            free: None,
            locked: None,
        }
    }
}

