/*
 * Binance COIN-M Futures API
 *
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::cmfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CmfuturesCreateBatchOrdersV1RespInner {
    CmfuturesCreateBatchOrdersV1RespItem(Box<models::CmfuturesCreateBatchOrdersV1RespItem>),
    ApiError(Box<models::ApiError>),
}

impl Default for CmfuturesCreateBatchOrdersV1RespInner {
    fn default() -> Self {
        Self::CmfuturesCreateBatchOrdersV1RespItem(Default::default())
    }
}

