/*
 * Binance COIN-M Futures API
 *
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::cmfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBalanceV1RespItem {
    #[serde(rename = "accountAlias", skip_serializing_if = "Option::is_none")]
    pub account_alias: Option<String>,
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "availableBalance", skip_serializing_if = "Option::is_none")]
    pub available_balance: Option<String>,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
    #[serde(rename = "crossUnPnl", skip_serializing_if = "Option::is_none")]
    pub cross_un_pnl: Option<String>,
    #[serde(rename = "crossWalletBalance", skip_serializing_if = "Option::is_none")]
    pub cross_wallet_balance: Option<String>,
    #[serde(rename = "updateTime", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<i64>,
    #[serde(rename = "withdrawAvailable", skip_serializing_if = "Option::is_none")]
    pub withdraw_available: Option<String>,
}

impl GetBalanceV1RespItem {
    pub fn new() -> GetBalanceV1RespItem {
        GetBalanceV1RespItem {
            account_alias: None,
            asset: None,
            available_balance: None,
            balance: None,
            cross_un_pnl: None,
            cross_wallet_balance: None,
            update_time: None,
            withdraw_available: None,
        }
    }
}

