/*
 * Binance COIN-M Futures API
 *
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::cmfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLeverageBracketV2RespItem {
    #[serde(rename = "brackets", skip_serializing_if = "Option::is_none")]
    pub brackets: Option<Vec<models::GetLeverageBracketV1RespItemBracketsInner>>,
    #[serde(rename = "notionalCoef", skip_serializing_if = "Option::is_none")]
    pub notional_coef: Option<f64>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
}

impl GetLeverageBracketV2RespItem {
    pub fn new() -> GetLeverageBracketV2RespItem {
        GetLeverageBracketV2RespItem {
            brackets: None,
            notional_coef: None,
            symbol: None,
        }
    }
}

