/*
 * Binance COIN-M Futures API
 *
 * OpenAPI specification for Binance exchange - Cmfutures API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::cmfutures::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAdlQuantileV1RespItemAdlQuantile {
    #[serde(rename = "HEDGE", skip_serializing_if = "Option::is_none")]
    pub hedge: Option<i32>,
    #[serde(rename = "LONG", skip_serializing_if = "Option::is_none")]
    pub long: Option<i32>,
    #[serde(rename = "SHORT", skip_serializing_if = "Option::is_none")]
    pub short: Option<i32>,
}

impl GetAdlQuantileV1RespItemAdlQuantile {
    pub fn new() -> GetAdlQuantileV1RespItemAdlQuantile {
        GetAdlQuantileV1RespItemAdlQuantile {
            hedge: None,
            long: None,
            short: None,
        }
    }
}

