/*
 * Binance Convert API
 *
 * OpenAPI specification for Binance exchange - Convert API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::convert::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConvertCreateConvertLimitQueryOpenOrdersV1RespListInner {
    #[serde(rename = "createTime", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<i64>,
    #[serde(rename = "expiredTimestamp", skip_serializing_if = "Option::is_none")]
    pub expired_timestamp: Option<i64>,
    #[serde(rename = "fromAmount", skip_serializing_if = "Option::is_none")]
    pub from_amount: Option<String>,
    #[serde(rename = "fromAsset", skip_serializing_if = "Option::is_none")]
    pub from_asset: Option<String>,
    #[serde(rename = "inverseRatio", skip_serializing_if = "Option::is_none")]
    pub inverse_ratio: Option<String>,
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i64>,
    #[serde(rename = "orderStatus", skip_serializing_if = "Option::is_none")]
    pub order_status: Option<String>,
    #[serde(rename = "quoteId", skip_serializing_if = "Option::is_none")]
    pub quote_id: Option<String>,
    #[serde(rename = "ratio", skip_serializing_if = "Option::is_none")]
    pub ratio: Option<String>,
    #[serde(rename = "toAmount", skip_serializing_if = "Option::is_none")]
    pub to_amount: Option<String>,
    #[serde(rename = "toAsset", skip_serializing_if = "Option::is_none")]
    pub to_asset: Option<String>,
}

impl ConvertCreateConvertLimitQueryOpenOrdersV1RespListInner {
    pub fn new() -> ConvertCreateConvertLimitQueryOpenOrdersV1RespListInner {
        ConvertCreateConvertLimitQueryOpenOrdersV1RespListInner {
            create_time: None,
            expired_timestamp: None,
            from_amount: None,
            from_asset: None,
            inverse_ratio: None,
            order_id: None,
            order_status: None,
            quote_id: None,
            ratio: None,
            to_amount: None,
            to_asset: None,
        }
    }
}

