/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSubAccountFuturesInternalTransferV1Resp {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "txnId", skip_serializing_if = "Option::is_none")]
    pub txn_id: Option<String>,
}

impl CreateSubAccountFuturesInternalTransferV1Resp {
    pub fn new() -> CreateSubAccountFuturesInternalTransferV1Resp {
        CreateSubAccountFuturesInternalTransferV1Resp {
            success: None,
            txn_id: None,
        }
    }
}

