/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDciProductSubscribeV1Resp {
    #[serde(rename = "apr", skip_serializing_if = "Option::is_none")]
    pub apr: Option<String>,
    #[serde(rename = "autoCompoundPlan", skip_serializing_if = "Option::is_none")]
    pub auto_compound_plan: Option<String>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    #[serde(rename = "exercisedCoin", skip_serializing_if = "Option::is_none")]
    pub exercised_coin: Option<String>,
    #[serde(rename = "investCoin", skip_serializing_if = "Option::is_none")]
    pub invest_coin: Option<String>,
    #[serde(rename = "optionType", skip_serializing_if = "Option::is_none")]
    pub option_type: Option<String>,
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i64>,
    #[serde(rename = "positionId", skip_serializing_if = "Option::is_none")]
    pub position_id: Option<i64>,
    #[serde(rename = "purchaseStatus", skip_serializing_if = "Option::is_none")]
    pub purchase_status: Option<String>,
    #[serde(rename = "purchaseTime", skip_serializing_if = "Option::is_none")]
    pub purchase_time: Option<i64>,
    #[serde(rename = "settleDate", skip_serializing_if = "Option::is_none")]
    pub settle_date: Option<i32>,
    #[serde(rename = "strikePrice", skip_serializing_if = "Option::is_none")]
    pub strike_price: Option<String>,
    #[serde(rename = "subscriptionAmount", skip_serializing_if = "Option::is_none")]
    pub subscription_amount: Option<String>,
}

impl CreateDciProductSubscribeV1Resp {
    pub fn new() -> CreateDciProductSubscribeV1Resp {
        CreateDciProductSubscribeV1Resp {
            apr: None,
            auto_compound_plan: None,
            duration: None,
            exercised_coin: None,
            invest_coin: None,
            option_type: None,
            order_id: None,
            position_id: None,
            purchase_status: None,
            purchase_time: None,
            settle_date: None,
            strike_price: None,
            subscription_amount: None,
        }
    }
}

