/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSubAccountUniversalTransferV1Resp {
    #[serde(rename = "clientTranId", skip_serializing_if = "Option::is_none")]
    pub client_tran_id: Option<String>,
    #[serde(rename = "tranId", skip_serializing_if = "Option::is_none")]
    pub tran_id: Option<i64>,
}

impl CreateSubAccountUniversalTransferV1Resp {
    pub fn new() -> CreateSubAccountUniversalTransferV1Resp {
        CreateSubAccountUniversalTransferV1Resp {
            client_tran_id: None,
            tran_id: None,
        }
    }
}

