/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateLoanFlexibleRepayCollateralV2Resp {
    #[serde(rename = "collateralCoin", skip_serializing_if = "Option::is_none")]
    pub collateral_coin: Option<String>,
    #[serde(rename = "currentLTV", skip_serializing_if = "Option::is_none")]
    pub current_ltv: Option<String>,
    #[serde(rename = "fullRepayment", skip_serializing_if = "Option::is_none")]
    pub full_repayment: Option<bool>,
    #[serde(rename = "loanCoin", skip_serializing_if = "Option::is_none")]
    pub loan_coin: Option<String>,
    #[serde(rename = "remainingCollateral", skip_serializing_if = "Option::is_none")]
    pub remaining_collateral: Option<String>,
    #[serde(rename = "remainingDebt", skip_serializing_if = "Option::is_none")]
    pub remaining_debt: Option<String>,
    #[serde(rename = "repayStatus", skip_serializing_if = "Option::is_none")]
    pub repay_status: Option<String>,
}

impl CreateLoanFlexibleRepayCollateralV2Resp {
    pub fn new() -> CreateLoanFlexibleRepayCollateralV2Resp {
        CreateLoanFlexibleRepayCollateralV2Resp {
            collateral_coin: None,
            current_ltv: None,
            full_repayment: None,
            loan_coin: None,
            remaining_collateral: None,
            remaining_debt: None,
            repay_status: None,
        }
    }
}

