/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBrokerSubAccountBnbBurnMarginInterestV1Resp {
    #[serde(rename = "interestBNBBurn", skip_serializing_if = "Option::is_none")]
    pub interest_bnb_burn: Option<bool>,
    #[serde(rename = "subAccountId", skip_serializing_if = "Option::is_none")]
    pub sub_account_id: Option<i64>,
}

impl CreateBrokerSubAccountBnbBurnMarginInterestV1Resp {
    pub fn new() -> CreateBrokerSubAccountBnbBurnMarginInterestV1Resp {
        CreateBrokerSubAccountBnbBurnMarginInterestV1Resp {
            interest_bnb_burn: None,
            sub_account_id: None,
        }
    }
}

