/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSubAccountBlvtEnableV1Resp {
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "enableBlvt", skip_serializing_if = "Option::is_none")]
    pub enable_blvt: Option<bool>,
}

impl CreateSubAccountBlvtEnableV1Resp {
    pub fn new() -> CreateSubAccountBlvtEnableV1Resp {
        CreateSubAccountBlvtEnableV1Resp {
            email: None,
            enable_blvt: None,
        }
    }
}

