/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateLoanVipRepayV1Resp {
    #[serde(rename = "collateralCoin", skip_serializing_if = "Option::is_none")]
    pub collateral_coin: Option<String>,
    #[serde(rename = "currentLTV", skip_serializing_if = "Option::is_none")]
    pub current_ltv: Option<String>,
    #[serde(rename = "loanCoin", skip_serializing_if = "Option::is_none")]
    pub loan_coin: Option<String>,
    #[serde(rename = "remainingInterest", skip_serializing_if = "Option::is_none")]
    pub remaining_interest: Option<String>,
    #[serde(rename = "remainingPrincipal", skip_serializing_if = "Option::is_none")]
    pub remaining_principal: Option<String>,
    #[serde(rename = "repayAmount", skip_serializing_if = "Option::is_none")]
    pub repay_amount: Option<String>,
    #[serde(rename = "repayStatus", skip_serializing_if = "Option::is_none")]
    pub repay_status: Option<String>,
}

impl CreateLoanVipRepayV1Resp {
    pub fn new() -> CreateLoanVipRepayV1Resp {
        CreateLoanVipRepayV1Resp {
            collateral_coin: None,
            current_ltv: None,
            loan_coin: None,
            remaining_interest: None,
            remaining_principal: None,
            repay_amount: None,
            repay_status: None,
        }
    }
}

