/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteMarginIsolatedAccountV1Resp {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
}

impl DeleteMarginIsolatedAccountV1Resp {
    pub fn new() -> DeleteMarginIsolatedAccountV1Resp {
        DeleteMarginIsolatedAccountV1Resp {
            success: None,
            symbol: None,
        }
    }
}

