/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBrokerRebateFuturesRecentRecordV1RespItem {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "income", skip_serializing_if = "Option::is_none")]
    pub income: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
    #[serde(rename = "subaccountId", skip_serializing_if = "Option::is_none")]
    pub subaccount_id: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
    #[serde(rename = "tradeId", skip_serializing_if = "Option::is_none")]
    pub trade_id: Option<i64>,
}

impl GetBrokerRebateFuturesRecentRecordV1RespItem {
    pub fn new() -> GetBrokerRebateFuturesRecentRecordV1RespItem {
        GetBrokerRebateFuturesRecentRecordV1RespItem {
            asset: None,
            income: None,
            status: None,
            subaccount_id: None,
            symbol: None,
            time: None,
            trade_id: None,
        }
    }
}

