/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiningWorkerListV1RespData {
    #[serde(rename = "pageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    #[serde(rename = "totalNum", skip_serializing_if = "Option::is_none")]
    pub total_num: Option<i32>,
    #[serde(rename = "workerDatas", skip_serializing_if = "Option::is_none")]
    pub worker_datas: Option<Vec<models::GetMiningWorkerListV1RespDataWorkerDatasInner>>,
}

impl GetMiningWorkerListV1RespData {
    pub fn new() -> GetMiningWorkerListV1RespData {
        GetMiningWorkerListV1RespData {
            page_size: None,
            total_num: None,
            worker_datas: None,
        }
    }
}

