/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInner {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInnerData>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "updateTime", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<i64>,
}

impl GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInner {
    pub fn new() -> GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInner {
        GetManagedSubaccountFetchFutureAssetV1RespSnapshotVosInner {
            data: None,
            r#type: None,
            update_time: None,
        }
    }
}

