/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiningPaymentListV1RespData {
    #[serde(rename = "accountProfits", skip_serializing_if = "Option::is_none")]
    pub account_profits: Option<Vec<models::GetMiningPaymentListV1RespDataAccountProfitsInner>>,
    #[serde(rename = "pageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    #[serde(rename = "totalNum", skip_serializing_if = "Option::is_none")]
    pub total_num: Option<i32>,
}

impl GetMiningPaymentListV1RespData {
    pub fn new() -> GetMiningPaymentListV1RespData {
        GetMiningPaymentListV1RespData {
            account_profits: None,
            page_size: None,
            total_num: None,
        }
    }
}

