/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMiningStatisticsUserListV1RespDataInner {
    #[serde(rename = "list", skip_serializing_if = "Option::is_none")]
    pub list: Option<Vec<models::GetMiningStatisticsUserListV1RespDataInnerListInner>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "userName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl GetMiningStatisticsUserListV1RespDataInner {
    pub fn new() -> GetMiningStatisticsUserListV1RespDataInner {
        GetMiningStatisticsUserListV1RespDataInner {
            list: None,
            r#type: None,
            user_name: None,
        }
    }
}

