/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMarginInterestHistoryV1RespRowsInner {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "interest", skip_serializing_if = "Option::is_none")]
    pub interest: Option<String>,
    #[serde(rename = "interestAccuredTime", skip_serializing_if = "Option::is_none")]
    pub interest_accured_time: Option<i64>,
    #[serde(rename = "interestRate", skip_serializing_if = "Option::is_none")]
    pub interest_rate: Option<String>,
    #[serde(rename = "isolatedSymbol", skip_serializing_if = "Option::is_none")]
    pub isolated_symbol: Option<String>,
    #[serde(rename = "principal", skip_serializing_if = "Option::is_none")]
    pub principal: Option<String>,
    #[serde(rename = "rawAsset", skip_serializing_if = "Option::is_none")]
    pub raw_asset: Option<String>,
    #[serde(rename = "txId", skip_serializing_if = "Option::is_none")]
    pub tx_id: Option<i64>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl GetMarginInterestHistoryV1RespRowsInner {
    pub fn new() -> GetMarginInterestHistoryV1RespRowsInner {
        GetMarginInterestHistoryV1RespRowsInner {
            asset: None,
            interest: None,
            interest_accured_time: None,
            interest_rate: None,
            isolated_symbol: None,
            principal: None,
            raw_asset: None,
            tx_id: None,
            r#type: None,
        }
    }
}

