/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBrokerSubAccountApiCommissionFuturesV1RespItem {
    #[serde(rename = "makerCommission", skip_serializing_if = "Option::is_none")]
    pub maker_commission: Option<i32>,
    #[serde(rename = "subAccountId", skip_serializing_if = "Option::is_none")]
    pub sub_account_id: Option<i64>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "takerCommission", skip_serializing_if = "Option::is_none")]
    pub taker_commission: Option<i32>,
}

impl GetBrokerSubAccountApiCommissionFuturesV1RespItem {
    pub fn new() -> GetBrokerSubAccountApiCommissionFuturesV1RespItem {
        GetBrokerSubAccountApiCommissionFuturesV1RespItem {
            maker_commission: None,
            sub_account_id: None,
            symbol: None,
            taker_commission: None,
        }
    }
}

