/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFiatPaymentsV1RespDataInner {
    #[serde(rename = "createTime", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<i64>,
    #[serde(rename = "cryptoCurrency", skip_serializing_if = "Option::is_none")]
    pub crypto_currency: Option<String>,
    #[serde(rename = "fiatCurrency", skip_serializing_if = "Option::is_none")]
    pub fiat_currency: Option<String>,
    #[serde(rename = "obtainAmount", skip_serializing_if = "Option::is_none")]
    pub obtain_amount: Option<String>,
    #[serde(rename = "orderNo", skip_serializing_if = "Option::is_none")]
    pub order_no: Option<String>,
    #[serde(rename = "paymentMethod", skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<String>,
    #[serde(rename = "sourceAmount", skip_serializing_if = "Option::is_none")]
    pub source_amount: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "totalFee", skip_serializing_if = "Option::is_none")]
    pub total_fee: Option<String>,
    #[serde(rename = "updateTime", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<i64>,
}

impl GetFiatPaymentsV1RespDataInner {
    pub fn new() -> GetFiatPaymentsV1RespDataInner {
        GetFiatPaymentsV1RespDataInner {
            create_time: None,
            crypto_currency: None,
            fiat_currency: None,
            obtain_amount: None,
            order_no: None,
            payment_method: None,
            price: None,
            source_amount: None,
            status: None,
            total_fee: None,
            update_time: None,
        }
    }
}

