/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMarginNextHourlyInterestRateV1RespItem {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "nextHourlyInterestRate", skip_serializing_if = "Option::is_none")]
    pub next_hourly_interest_rate: Option<String>,
}

impl GetMarginNextHourlyInterestRateV1RespItem {
    pub fn new() -> GetMarginNextHourlyInterestRateV1RespItem {
        GetMarginNextHourlyInterestRateV1RespItem {
            asset: None,
            next_hourly_interest_rate: None,
        }
    }
}

