/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPortfolioCollateralRateV2RespItemCollateralInfoInner {
    #[serde(rename = "collateralRate", skip_serializing_if = "Option::is_none")]
    pub collateral_rate: Option<String>,
    #[serde(rename = "cum", skip_serializing_if = "Option::is_none")]
    pub cum: Option<String>,
    #[serde(rename = "tierCap", skip_serializing_if = "Option::is_none")]
    pub tier_cap: Option<String>,
    #[serde(rename = "tierFloor", skip_serializing_if = "Option::is_none")]
    pub tier_floor: Option<String>,
}

impl GetPortfolioCollateralRateV2RespItemCollateralInfoInner {
    pub fn new() -> GetPortfolioCollateralRateV2RespItemCollateralInfoInner {
        GetPortfolioCollateralRateV2RespItemCollateralInfoInner {
            collateral_rate: None,
            cum: None,
            tier_cap: None,
            tier_floor: None,
        }
    }
}

