/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSolStakingSolQuotaV1Resp {
    #[serde(rename = "calculating", skip_serializing_if = "Option::is_none")]
    pub calculating: Option<bool>,
    #[serde(rename = "commissionFee", skip_serializing_if = "Option::is_none")]
    pub commission_fee: Option<String>,
    #[serde(rename = "leftRedemptionPersonalQuota", skip_serializing_if = "Option::is_none")]
    pub left_redemption_personal_quota: Option<String>,
    #[serde(rename = "leftStakingPersonalQuota", skip_serializing_if = "Option::is_none")]
    pub left_staking_personal_quota: Option<String>,
    #[serde(rename = "minRedeemAmount", skip_serializing_if = "Option::is_none")]
    pub min_redeem_amount: Option<String>,
    #[serde(rename = "minStakeAmount", skip_serializing_if = "Option::is_none")]
    pub min_stake_amount: Option<String>,
    #[serde(rename = "nextEpochTime", skip_serializing_if = "Option::is_none")]
    pub next_epoch_time: Option<i64>,
    #[serde(rename = "redeemPeriod", skip_serializing_if = "Option::is_none")]
    pub redeem_period: Option<i32>,
    #[serde(rename = "redeemable", skip_serializing_if = "Option::is_none")]
    pub redeemable: Option<bool>,
    #[serde(rename = "soldOut", skip_serializing_if = "Option::is_none")]
    pub sold_out: Option<bool>,
    #[serde(rename = "stakeable", skip_serializing_if = "Option::is_none")]
    pub stakeable: Option<bool>,
}

impl GetSolStakingSolQuotaV1Resp {
    pub fn new() -> GetSolStakingSolQuotaV1Resp {
        GetSolStakingSolQuotaV1Resp {
            calculating: None,
            commission_fee: None,
            left_redemption_personal_quota: None,
            left_staking_personal_quota: None,
            min_redeem_amount: None,
            min_stake_amount: None,
            next_epoch_time: None,
            redeem_period: None,
            redeemable: None,
            sold_out: None,
            stakeable: None,
        }
    }
}

