/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetConvertExchangeInfoV1RespItem {
    #[serde(rename = "fromAsset", skip_serializing_if = "Option::is_none")]
    pub from_asset: Option<String>,
    #[serde(rename = "fromAssetMaxAmount", skip_serializing_if = "Option::is_none")]
    pub from_asset_max_amount: Option<String>,
    #[serde(rename = "fromAssetMinAmount", skip_serializing_if = "Option::is_none")]
    pub from_asset_min_amount: Option<String>,
    #[serde(rename = "toAsset", skip_serializing_if = "Option::is_none")]
    pub to_asset: Option<String>,
    #[serde(rename = "toAssetMaxAmount", skip_serializing_if = "Option::is_none")]
    pub to_asset_max_amount: Option<String>,
    #[serde(rename = "toAssetMinAmount", skip_serializing_if = "Option::is_none")]
    pub to_asset_min_amount: Option<String>,
}

impl GetConvertExchangeInfoV1RespItem {
    pub fn new() -> GetConvertExchangeInfoV1RespItem {
        GetConvertExchangeInfoV1RespItem {
            from_asset: None,
            from_asset_max_amount: None,
            from_asset_min_amount: None,
            to_asset: None,
            to_asset_max_amount: None,
            to_asset_min_amount: None,
        }
    }
}

