/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner {
    #[serde(rename = "adjustTime", skip_serializing_if = "Option::is_none")]
    pub adjust_time: Option<i64>,
    #[serde(rename = "afterLTV", skip_serializing_if = "Option::is_none")]
    pub after_ltv: Option<String>,
    #[serde(rename = "collateralAmount", skip_serializing_if = "Option::is_none")]
    pub collateral_amount: Option<String>,
    #[serde(rename = "collateralCoin", skip_serializing_if = "Option::is_none")]
    pub collateral_coin: Option<String>,
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<String>,
    #[serde(rename = "loanCoin", skip_serializing_if = "Option::is_none")]
    pub loan_coin: Option<String>,
    #[serde(rename = "preLTV", skip_serializing_if = "Option::is_none")]
    pub pre_ltv: Option<String>,
}

impl GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner {
    pub fn new() -> GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner {
        GetLoanFlexibleLtvAdjustmentHistoryV2RespRowsInner {
            adjust_time: None,
            after_ltv: None,
            collateral_amount: None,
            collateral_coin: None,
            direction: None,
            loan_coin: None,
            pre_ltv: None,
        }
    }
}

