/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSubAccountFuturesAccountSummaryV1Resp {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "subAccountList", skip_serializing_if = "Option::is_none")]
    pub sub_account_list: Option<Vec<models::GetSubAccountFuturesAccountSummaryV1RespSubAccountListInner>>,
    #[serde(rename = "totalInitialMargin", skip_serializing_if = "Option::is_none")]
    pub total_initial_margin: Option<String>,
    #[serde(rename = "totalMaintenanceMargin", skip_serializing_if = "Option::is_none")]
    pub total_maintenance_margin: Option<String>,
    #[serde(rename = "totalMarginBalance", skip_serializing_if = "Option::is_none")]
    pub total_margin_balance: Option<String>,
    #[serde(rename = "totalOpenOrderInitialMargin", skip_serializing_if = "Option::is_none")]
    pub total_open_order_initial_margin: Option<String>,
    #[serde(rename = "totalPositionInitialMargin", skip_serializing_if = "Option::is_none")]
    pub total_position_initial_margin: Option<String>,
    #[serde(rename = "totalUnrealizedProfit", skip_serializing_if = "Option::is_none")]
    pub total_unrealized_profit: Option<String>,
    #[serde(rename = "totalWalletBalance", skip_serializing_if = "Option::is_none")]
    pub total_wallet_balance: Option<String>,
}

impl GetSubAccountFuturesAccountSummaryV1Resp {
    pub fn new() -> GetSubAccountFuturesAccountSummaryV1Resp {
        GetSubAccountFuturesAccountSummaryV1Resp {
            asset: None,
            sub_account_list: None,
            total_initial_margin: None,
            total_maintenance_margin: None,
            total_margin_balance: None,
            total_open_order_initial_margin: None,
            total_position_initial_margin: None,
            total_unrealized_profit: None,
            total_wallet_balance: None,
        }
    }
}

