/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApiReferralIfNewUserV1Resp {
    #[serde(rename = "apiAgentCode", skip_serializing_if = "Option::is_none")]
    pub api_agent_code: Option<String>,
    #[serde(rename = "ifNewUser", skip_serializing_if = "Option::is_none")]
    pub if_new_user: Option<bool>,
    #[serde(rename = "rebateWorking", skip_serializing_if = "Option::is_none")]
    pub rebate_working: Option<bool>,
    #[serde(rename = "referrerId", skip_serializing_if = "Option::is_none")]
    pub referrer_id: Option<i64>,
}

impl GetApiReferralIfNewUserV1Resp {
    pub fn new() -> GetApiReferralIfNewUserV1Resp {
        GetApiReferralIfNewUserV1Resp {
            api_agent_code: None,
            if_new_user: None,
            rebate_working: None,
            referrer_id: None,
        }
    }
}

