/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSimpleEarnFlexibleListV1RespRowsInner {
    #[serde(rename = "airDropPercentageRate", skip_serializing_if = "Option::is_none")]
    pub air_drop_percentage_rate: Option<String>,
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "canPurchase", skip_serializing_if = "Option::is_none")]
    pub can_purchase: Option<bool>,
    #[serde(rename = "canRedeem", skip_serializing_if = "Option::is_none")]
    pub can_redeem: Option<bool>,
    #[serde(rename = "hot", skip_serializing_if = "Option::is_none")]
    pub hot: Option<bool>,
    #[serde(rename = "isSoldOut", skip_serializing_if = "Option::is_none")]
    pub is_sold_out: Option<bool>,
    #[serde(rename = "latestAnnualPercentageRate", skip_serializing_if = "Option::is_none")]
    pub latest_annual_percentage_rate: Option<String>,
    #[serde(rename = "minPurchaseAmount", skip_serializing_if = "Option::is_none")]
    pub min_purchase_amount: Option<String>,
    #[serde(rename = "productId", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "subscriptionStartTime", skip_serializing_if = "Option::is_none")]
    pub subscription_start_time: Option<String>,
    #[serde(rename = "tierAnnualPercentageRate", skip_serializing_if = "Option::is_none")]
    pub tier_annual_percentage_rate: Option<Box<models::GetSimpleEarnFlexibleListV1RespRowsInnerTierAnnualPercentageRate>>,
}

impl GetSimpleEarnFlexibleListV1RespRowsInner {
    pub fn new() -> GetSimpleEarnFlexibleListV1RespRowsInner {
        GetSimpleEarnFlexibleListV1RespRowsInner {
            air_drop_percentage_rate: None,
            asset: None,
            can_purchase: None,
            can_redeem: None,
            hot: None,
            is_sold_out: None,
            latest_annual_percentage_rate: None,
            min_purchase_amount: None,
            product_id: None,
            status: None,
            subscription_start_time: None,
            tier_annual_percentage_rate: None,
        }
    }
}

