/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNftHistoryTransactionsV1Resp {
    #[serde(rename = "list", skip_serializing_if = "Option::is_none")]
    pub list: Option<Vec<models::GetNftHistoryTransactionsV1RespListInner>>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl GetNftHistoryTransactionsV1Resp {
    pub fn new() -> GetNftHistoryTransactionsV1Resp {
        GetNftHistoryTransactionsV1Resp {
            list: None,
            total: None,
        }
    }
}

