/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMarginTradeCoeffV1Resp {
    #[serde(rename = "forceLiquidationBar", skip_serializing_if = "Option::is_none")]
    pub force_liquidation_bar: Option<String>,
    #[serde(rename = "marginCallBar", skip_serializing_if = "Option::is_none")]
    pub margin_call_bar: Option<String>,
    #[serde(rename = "normalBar", skip_serializing_if = "Option::is_none")]
    pub normal_bar: Option<String>,
}

impl GetMarginTradeCoeffV1Resp {
    pub fn new() -> GetMarginTradeCoeffV1Resp {
        GetMarginTradeCoeffV1Resp {
            force_liquidation_bar: None,
            margin_call_bar: None,
            normal_bar: None,
        }
    }
}

