/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMarginLeverageBracketV1RespItemBracketsInner {
    #[serde(rename = "fastNum", skip_serializing_if = "Option::is_none")]
    pub fast_num: Option<i32>,
    #[serde(rename = "initialMarginRate", skip_serializing_if = "Option::is_none")]
    pub initial_margin_rate: Option<f64>,
    #[serde(rename = "leverage", skip_serializing_if = "Option::is_none")]
    pub leverage: Option<i32>,
    #[serde(rename = "maintenanceMarginRate", skip_serializing_if = "Option::is_none")]
    pub maintenance_margin_rate: Option<f64>,
    #[serde(rename = "maxDebt", skip_serializing_if = "Option::is_none")]
    pub max_debt: Option<i32>,
}

impl GetMarginLeverageBracketV1RespItemBracketsInner {
    pub fn new() -> GetMarginLeverageBracketV1RespItemBracketsInner {
        GetMarginLeverageBracketV1RespItemBracketsInner {
            fast_num: None,
            initial_margin_rate: None,
            leverage: None,
            maintenance_margin_rate: None,
            max_debt: None,
        }
    }
}

