/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetC2cOrderMatchListUserOrderHistoryV1RespDataInner {
    #[serde(rename = "advNo", skip_serializing_if = "Option::is_none")]
    pub adv_no: Option<String>,
    #[serde(rename = "advertisementRole", skip_serializing_if = "Option::is_none")]
    pub advertisement_role: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "commission", skip_serializing_if = "Option::is_none")]
    pub commission: Option<String>,
    #[serde(rename = "counterPartNickName", skip_serializing_if = "Option::is_none")]
    pub counter_part_nick_name: Option<String>,
    #[serde(rename = "createTime", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<i64>,
    #[serde(rename = "fiat", skip_serializing_if = "Option::is_none")]
    pub fiat: Option<String>,
    #[serde(rename = "fiatSymbol", skip_serializing_if = "Option::is_none")]
    pub fiat_symbol: Option<String>,
    #[serde(rename = "orderNumber", skip_serializing_if = "Option::is_none")]
    pub order_number: Option<String>,
    #[serde(rename = "orderStatus", skip_serializing_if = "Option::is_none")]
    pub order_status: Option<String>,
    #[serde(rename = "totalPrice", skip_serializing_if = "Option::is_none")]
    pub total_price: Option<String>,
    #[serde(rename = "tradeType", skip_serializing_if = "Option::is_none")]
    pub trade_type: Option<String>,
    #[serde(rename = "unitPrice", skip_serializing_if = "Option::is_none")]
    pub unit_price: Option<String>,
}

impl GetC2cOrderMatchListUserOrderHistoryV1RespDataInner {
    pub fn new() -> GetC2cOrderMatchListUserOrderHistoryV1RespDataInner {
        GetC2cOrderMatchListUserOrderHistoryV1RespDataInner {
            adv_no: None,
            advertisement_role: None,
            amount: None,
            asset: None,
            commission: None,
            counter_part_nick_name: None,
            create_time: None,
            fiat: None,
            fiat_symbol: None,
            order_number: None,
            order_status: None,
            total_price: None,
            trade_type: None,
            unit_price: None,
        }
    }
}

