/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLoanRepayHistoryV1Resp {
    #[serde(rename = "rows", skip_serializing_if = "Option::is_none")]
    pub rows: Option<Vec<models::GetLoanRepayHistoryV1RespRowsInner>>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl GetLoanRepayHistoryV1Resp {
    pub fn new() -> GetLoanRepayHistoryV1Resp {
        GetLoanRepayHistoryV1Resp {
            rows: None,
            total: None,
        }
    }
}

