/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSolStakingSolHistoryRedemptionHistoryV1RespRowsInner {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "arrivalTime", skip_serializing_if = "Option::is_none")]
    pub arrival_time: Option<i64>,
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "distributeAmount", skip_serializing_if = "Option::is_none")]
    pub distribute_amount: Option<String>,
    #[serde(rename = "distributeAsset", skip_serializing_if = "Option::is_none")]
    pub distribute_asset: Option<String>,
    #[serde(rename = "exchangeRate", skip_serializing_if = "Option::is_none")]
    pub exchange_rate: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
}

impl GetSolStakingSolHistoryRedemptionHistoryV1RespRowsInner {
    pub fn new() -> GetSolStakingSolHistoryRedemptionHistoryV1RespRowsInner {
        GetSolStakingSolHistoryRedemptionHistoryV1RespRowsInner {
            amount: None,
            arrival_time: None,
            asset: None,
            distribute_amount: None,
            distribute_asset: None,
            exchange_rate: None,
            status: None,
            time: None,
        }
    }
}

