/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLoanFlexibleLoanableDataV2RespRowsInner {
    #[serde(rename = "flexibleInterestRate", skip_serializing_if = "Option::is_none")]
    pub flexible_interest_rate: Option<String>,
    #[serde(rename = "flexibleMaxLimit", skip_serializing_if = "Option::is_none")]
    pub flexible_max_limit: Option<String>,
    #[serde(rename = "flexibleMinLimit", skip_serializing_if = "Option::is_none")]
    pub flexible_min_limit: Option<String>,
    #[serde(rename = "loanCoin", skip_serializing_if = "Option::is_none")]
    pub loan_coin: Option<String>,
}

impl GetLoanFlexibleLoanableDataV2RespRowsInner {
    pub fn new() -> GetLoanFlexibleLoanableDataV2RespRowsInner {
        GetLoanFlexibleLoanableDataV2RespRowsInner {
            flexible_interest_rate: None,
            flexible_max_limit: None,
            flexible_min_limit: None,
            loan_coin: None,
        }
    }
}

