/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSolStakingSolHistoryBnsolRewardsHistoryV1Resp {
    #[serde(rename = "estRewardsInSOL", skip_serializing_if = "Option::is_none")]
    pub est_rewards_in_sol: Option<String>,
    #[serde(rename = "rows", skip_serializing_if = "Option::is_none")]
    pub rows: Option<Vec<models::GetSolStakingSolHistoryBnsolRewardsHistoryV1RespRowsInner>>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl GetSolStakingSolHistoryBnsolRewardsHistoryV1Resp {
    pub fn new() -> GetSolStakingSolHistoryBnsolRewardsHistoryV1Resp {
        GetSolStakingSolHistoryBnsolRewardsHistoryV1Resp {
            est_rewards_in_sol: None,
            rows: None,
            total: None,
        }
    }
}

