/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLocalentityVaspV1RespItem {
    #[serde(rename = "vaspCode", skip_serializing_if = "Option::is_none")]
    pub vasp_code: Option<String>,
    #[serde(rename = "vaspName", skip_serializing_if = "Option::is_none")]
    pub vasp_name: Option<String>,
}

impl GetLocalentityVaspV1RespItem {
    pub fn new() -> GetLocalentityVaspV1RespItem {
        GetLocalentityVaspV1RespItem {
            vasp_code: None,
            vasp_name: None,
        }
    }
}

