/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRebateTaxQueryV1RespData {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::GetRebateTaxQueryV1RespDataDataInner>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    #[serde(rename = "totalPageNum", skip_serializing_if = "Option::is_none")]
    pub total_page_num: Option<i32>,
    #[serde(rename = "totalRecords", skip_serializing_if = "Option::is_none")]
    pub total_records: Option<i32>,
}

impl GetRebateTaxQueryV1RespData {
    pub fn new() -> GetRebateTaxQueryV1RespData {
        GetRebateTaxQueryV1RespData {
            data: None,
            page: None,
            total_page_num: None,
            total_records: None,
        }
    }
}

