/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSubAccountSpotSummaryV1Resp {
    #[serde(rename = "masterAccountTotalAsset", skip_serializing_if = "Option::is_none")]
    pub master_account_total_asset: Option<String>,
    #[serde(rename = "spotSubUserAssetBtcVoList", skip_serializing_if = "Option::is_none")]
    pub spot_sub_user_asset_btc_vo_list: Option<Vec<models::GetSubAccountSpotSummaryV1RespSpotSubUserAssetBtcVoListInner>>,
    #[serde(rename = "totalCount", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
}

impl GetSubAccountSpotSummaryV1Resp {
    pub fn new() -> GetSubAccountSpotSummaryV1Resp {
        GetSubAccountSpotSummaryV1Resp {
            master_account_total_asset: None,
            spot_sub_user_asset_btc_vo_list: None,
            total_count: None,
        }
    }
}

