/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSubAccountFuturesMovePositionV1Resp {
    #[serde(rename = "futureMovePositionOrderVoList", skip_serializing_if = "Option::is_none")]
    pub future_move_position_order_vo_list: Option<Vec<models::GetSubAccountFuturesMovePositionV1RespFutureMovePositionOrderVoListInner>>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl GetSubAccountFuturesMovePositionV1Resp {
    pub fn new() -> GetSubAccountFuturesMovePositionV1Resp {
        GetSubAccountFuturesMovePositionV1Resp {
            future_move_position_order_vo_list: None,
            total: None,
        }
    }
}

