/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetManagedSubaccountAssetV1RespItem {
    #[serde(rename = "availableBalance", skip_serializing_if = "Option::is_none")]
    pub available_balance: Option<String>,
    #[serde(rename = "btcValue", skip_serializing_if = "Option::is_none")]
    pub btc_value: Option<String>,
    #[serde(rename = "coin", skip_serializing_if = "Option::is_none")]
    pub coin: Option<String>,
    #[serde(rename = "inOrder", skip_serializing_if = "Option::is_none")]
    pub in_order: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "totalBalance", skip_serializing_if = "Option::is_none")]
    pub total_balance: Option<String>,
}

impl GetManagedSubaccountAssetV1RespItem {
    pub fn new() -> GetManagedSubaccountAssetV1RespItem {
        GetManagedSubaccountAssetV1RespItem {
            available_balance: None,
            btc_value: None,
            coin: None,
            in_order: None,
            name: None,
            total_balance: None,
        }
    }
}

