/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNftHistoryTransactionsV1RespListInnerTokensInner {
    #[serde(rename = "contractAddress", skip_serializing_if = "Option::is_none")]
    pub contract_address: Option<String>,
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<String>,
    #[serde(rename = "tokenId", skip_serializing_if = "Option::is_none")]
    pub token_id: Option<String>,
}

impl GetNftHistoryTransactionsV1RespListInnerTokensInner {
    pub fn new() -> GetNftHistoryTransactionsV1RespListInnerTokensInner {
        GetNftHistoryTransactionsV1RespListInnerTokensInner {
            contract_address: None,
            network: None,
            token_id: None,
        }
    }
}

