/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMarginAccountV1Resp {
    #[serde(rename = "TotalCollateralValueInUSDT", skip_serializing_if = "Option::is_none")]
    pub total_collateral_value_in_usdt: Option<String>,
    #[serde(rename = "accountType", skip_serializing_if = "Option::is_none")]
    pub account_type: Option<String>,
    #[serde(rename = "borrowEnabled", skip_serializing_if = "Option::is_none")]
    pub borrow_enabled: Option<bool>,
    #[serde(rename = "collateralMarginLevel", skip_serializing_if = "Option::is_none")]
    pub collateral_margin_level: Option<String>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<bool>,
    #[serde(rename = "marginLevel", skip_serializing_if = "Option::is_none")]
    pub margin_level: Option<String>,
    #[serde(rename = "totalAssetOfBtc", skip_serializing_if = "Option::is_none")]
    pub total_asset_of_btc: Option<String>,
    #[serde(rename = "totalLiabilityOfBtc", skip_serializing_if = "Option::is_none")]
    pub total_liability_of_btc: Option<String>,
    #[serde(rename = "totalNetAssetOfBtc", skip_serializing_if = "Option::is_none")]
    pub total_net_asset_of_btc: Option<String>,
    #[serde(rename = "totalOpenOrderLossInUSDT", skip_serializing_if = "Option::is_none")]
    pub total_open_order_loss_in_usdt: Option<String>,
    #[serde(rename = "tradeEnabled", skip_serializing_if = "Option::is_none")]
    pub trade_enabled: Option<bool>,
    #[serde(rename = "transferInEnabled", skip_serializing_if = "Option::is_none")]
    pub transfer_in_enabled: Option<bool>,
    #[serde(rename = "transferOutEnabled", skip_serializing_if = "Option::is_none")]
    pub transfer_out_enabled: Option<bool>,
    #[serde(rename = "userAssets", skip_serializing_if = "Option::is_none")]
    pub user_assets: Option<Vec<models::GetManagedSubaccountMarginAssetV1RespUserAssetsInner>>,
}

impl GetMarginAccountV1Resp {
    pub fn new() -> GetMarginAccountV1Resp {
        GetMarginAccountV1Resp {
            total_collateral_value_in_usdt: None,
            account_type: None,
            borrow_enabled: None,
            collateral_margin_level: None,
            created: None,
            margin_level: None,
            total_asset_of_btc: None,
            total_liability_of_btc: None,
            total_net_asset_of_btc: None,
            total_open_order_loss_in_usdt: None,
            trade_enabled: None,
            transfer_in_enabled: None,
            transfer_out_enabled: None,
            user_assets: None,
        }
    }
}

