/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMarginIsolatedAccountV1RespAssetsInnerBaseAsset {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "borrowEnabled", skip_serializing_if = "Option::is_none")]
    pub borrow_enabled: Option<bool>,
    #[serde(rename = "borrowed", skip_serializing_if = "Option::is_none")]
    pub borrowed: Option<String>,
    #[serde(rename = "free", skip_serializing_if = "Option::is_none")]
    pub free: Option<String>,
    #[serde(rename = "interest", skip_serializing_if = "Option::is_none")]
    pub interest: Option<String>,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<String>,
    #[serde(rename = "netAsset", skip_serializing_if = "Option::is_none")]
    pub net_asset: Option<String>,
    #[serde(rename = "netAssetOfBtc", skip_serializing_if = "Option::is_none")]
    pub net_asset_of_btc: Option<String>,
    #[serde(rename = "repayEnabled", skip_serializing_if = "Option::is_none")]
    pub repay_enabled: Option<bool>,
    #[serde(rename = "totalAsset", skip_serializing_if = "Option::is_none")]
    pub total_asset: Option<String>,
}

impl GetMarginIsolatedAccountV1RespAssetsInnerBaseAsset {
    pub fn new() -> GetMarginIsolatedAccountV1RespAssetsInnerBaseAsset {
        GetMarginIsolatedAccountV1RespAssetsInnerBaseAsset {
            asset: None,
            borrow_enabled: None,
            borrowed: None,
            free: None,
            interest: None,
            locked: None,
            net_asset: None,
            net_asset_of_btc: None,
            repay_enabled: None,
            total_asset: None,
        }
    }
}

