/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSimpleEarnAccountV1Resp {
    #[serde(rename = "totalAmountInBTC", skip_serializing_if = "Option::is_none")]
    pub total_amount_in_btc: Option<String>,
    #[serde(rename = "totalAmountInUSDT", skip_serializing_if = "Option::is_none")]
    pub total_amount_in_usdt: Option<String>,
    #[serde(rename = "totalFlexibleAmountInBTC", skip_serializing_if = "Option::is_none")]
    pub total_flexible_amount_in_btc: Option<String>,
    #[serde(rename = "totalFlexibleAmountInUSDT", skip_serializing_if = "Option::is_none")]
    pub total_flexible_amount_in_usdt: Option<String>,
    #[serde(rename = "totalLockedInBTC", skip_serializing_if = "Option::is_none")]
    pub total_locked_in_btc: Option<String>,
    #[serde(rename = "totalLockedInUSDT", skip_serializing_if = "Option::is_none")]
    pub total_locked_in_usdt: Option<String>,
}

impl GetSimpleEarnAccountV1Resp {
    pub fn new() -> GetSimpleEarnAccountV1Resp {
        GetSimpleEarnAccountV1Resp {
            total_amount_in_btc: None,
            total_amount_in_usdt: None,
            total_flexible_amount_in_btc: None,
            total_flexible_amount_in_usdt: None,
            total_locked_in_btc: None,
            total_locked_in_usdt: None,
        }
    }
}

