/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLoanLtvAdjustmentHistoryV1RespRowsInner {
    #[serde(rename = "adjustTime", skip_serializing_if = "Option::is_none")]
    pub adjust_time: Option<i64>,
    #[serde(rename = "afterLTV", skip_serializing_if = "Option::is_none")]
    pub after_ltv: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "collateralCoin", skip_serializing_if = "Option::is_none")]
    pub collateral_coin: Option<String>,
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<String>,
    #[serde(rename = "loanCoin", skip_serializing_if = "Option::is_none")]
    pub loan_coin: Option<String>,
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i64>,
    #[serde(rename = "preLTV", skip_serializing_if = "Option::is_none")]
    pub pre_ltv: Option<String>,
}

impl GetLoanLtvAdjustmentHistoryV1RespRowsInner {
    pub fn new() -> GetLoanLtvAdjustmentHistoryV1RespRowsInner {
        GetLoanLtvAdjustmentHistoryV1RespRowsInner {
            adjust_time: None,
            after_ltv: None,
            amount: None,
            collateral_coin: None,
            direction: None,
            loan_coin: None,
            order_id: None,
            pre_ltv: None,
        }
    }
}

