/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSolStakingSolHistoryBoostRewardsHistoryV1RespRowsInner {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "bnsolHolding", skip_serializing_if = "Option::is_none")]
    pub bnsol_holding: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl GetSolStakingSolHistoryBoostRewardsHistoryV1RespRowsInner {
    pub fn new() -> GetSolStakingSolHistoryBoostRewardsHistoryV1RespRowsInner {
        GetSolStakingSolHistoryBoostRewardsHistoryV1RespRowsInner {
            amount: None,
            bnsol_holding: None,
            status: None,
            time: None,
            token: None,
        }
    }
}

