/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetConvertTradeFlowV1Resp {
    #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<i64>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "list", skip_serializing_if = "Option::is_none")]
    pub list: Option<Vec<models::GetConvertTradeFlowV1RespListInner>>,
    #[serde(rename = "moreData", skip_serializing_if = "Option::is_none")]
    pub more_data: Option<bool>,
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i64>,
}

impl GetConvertTradeFlowV1Resp {
    pub fn new() -> GetConvertTradeFlowV1Resp {
        GetConvertTradeFlowV1Resp {
            end_time: None,
            limit: None,
            list: None,
            more_data: None,
            start_time: None,
        }
    }
}

