/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCopyTradingFuturesLeadSymbolV1Resp {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::GetCopyTradingFuturesLeadSymbolV1RespDataInner>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl GetCopyTradingFuturesLeadSymbolV1Resp {
    pub fn new() -> GetCopyTradingFuturesLeadSymbolV1Resp {
        GetCopyTradingFuturesLeadSymbolV1Resp {
            code: None,
            data: None,
            message: None,
        }
    }
}

