/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCapitalDepositHisrecV1RespItem {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "addressTag", skip_serializing_if = "Option::is_none")]
    pub address_tag: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "coin", skip_serializing_if = "Option::is_none")]
    pub coin: Option<String>,
    #[serde(rename = "completeTime", skip_serializing_if = "Option::is_none")]
    pub complete_time: Option<i64>,
    #[serde(rename = "confirmTimes", skip_serializing_if = "Option::is_none")]
    pub confirm_times: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "insertTime", skip_serializing_if = "Option::is_none")]
    pub insert_time: Option<i64>,
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
    #[serde(rename = "transferType", skip_serializing_if = "Option::is_none")]
    pub transfer_type: Option<i32>,
    #[serde(rename = "txId", skip_serializing_if = "Option::is_none")]
    pub tx_id: Option<String>,
    #[serde(rename = "unlockConfirm", skip_serializing_if = "Option::is_none")]
    pub unlock_confirm: Option<i32>,
    #[serde(rename = "walletType", skip_serializing_if = "Option::is_none")]
    pub wallet_type: Option<i32>,
}

impl GetCapitalDepositHisrecV1RespItem {
    pub fn new() -> GetCapitalDepositHisrecV1RespItem {
        GetCapitalDepositHisrecV1RespItem {
            address: None,
            address_tag: None,
            amount: None,
            coin: None,
            complete_time: None,
            confirm_times: None,
            id: None,
            insert_time: None,
            network: None,
            status: None,
            transfer_type: None,
            tx_id: None,
            unlock_confirm: None,
            wallet_type: None,
        }
    }
}

