/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMarginCrossMarginCollateralRatioV1RespItem {
    #[serde(rename = "assetNames", skip_serializing_if = "Option::is_none")]
    pub asset_names: Option<Vec<String>>,
    #[serde(rename = "collaterals", skip_serializing_if = "Option::is_none")]
    pub collaterals: Option<Vec<models::GetMarginCrossMarginCollateralRatioV1RespItemCollateralsInner>>,
}

impl GetMarginCrossMarginCollateralRatioV1RespItem {
    pub fn new() -> GetMarginCrossMarginCollateralRatioV1RespItem {
        GetMarginCrossMarginCollateralRatioV1RespItem {
            asset_names: None,
            collaterals: None,
        }
    }
}

