/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SpotGetTickerV3Resp {
    Array(Vec<models::SpotGetTickerV3RespItem>),
    SpotGetTickerV3RespItem(Box<models::SpotGetTickerV3RespItem>),
}

impl Default for SpotGetTickerV3Resp {
    fn default() -> Self {
        Self::Array(Default::default())
    }
}

