/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpotExchangeFilterExchangeMaxNumAlgoOrders {
    #[serde(rename = "filterType", skip_serializing_if = "Option::is_none")]
    pub filter_type: Option<String>,
    #[serde(rename = "maxNumAlgoOrders", skip_serializing_if = "Option::is_none")]
    pub max_num_algo_orders: Option<i32>,
}

impl SpotExchangeFilterExchangeMaxNumAlgoOrders {
    pub fn new() -> SpotExchangeFilterExchangeMaxNumAlgoOrders {
        SpotExchangeFilterExchangeMaxNumAlgoOrders {
            filter_type: None,
            max_num_algo_orders: None,
        }
    }
}

