/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SpotCreateOrderCancelReplaceV3DataCancelResponse {
    ApiError(Box<models::ApiError>),
    SpotCreateOrderCancelReplaceV3CancelResp(Box<models::SpotCreateOrderCancelReplaceV3CancelResp>),
}

impl Default for SpotCreateOrderCancelReplaceV3DataCancelResponse {
    fn default() -> Self {
        Self::ApiError(Default::default())
    }
}

