/*
 * Binance Spot API
 *
 * OpenAPI specification for Binance exchange - Spot API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spot::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpotGetAccountCommissionV3Resp {
    #[serde(rename = "discount", skip_serializing_if = "Option::is_none")]
    pub discount: Option<Box<models::SpotCreateOrderTestV3RespDiscount>>,
    #[serde(rename = "standardCommission", skip_serializing_if = "Option::is_none")]
    pub standard_commission: Option<Box<models::SpotGetAccountCommissionV3RespStandardCommission>>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "taxCommission", skip_serializing_if = "Option::is_none")]
    pub tax_commission: Option<Box<models::SpotGetAccountCommissionV3RespStandardCommission>>,
}

impl SpotGetAccountCommissionV3Resp {
    pub fn new() -> SpotGetAccountCommissionV3Resp {
        SpotGetAccountCommissionV3Resp {
            discount: None,
            standard_commission: None,
            symbol: None,
            tax_commission: None,
        }
    }
}

