/*
 * Binance Futures Data API
 *
 * OpenAPI specification for Binance exchange - Futuresdata API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::futuresdata::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FuturesdataGetFuturesHistDataLinkV1RespDataInner {
    #[serde(rename = "day", skip_serializing_if = "Option::is_none")]
    pub day: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl FuturesdataGetFuturesHistDataLinkV1RespDataInner {
    pub fn new() -> FuturesdataGetFuturesHistDataLinkV1RespDataInner {
        FuturesdataGetFuturesHistDataLinkV1RespDataInner {
            day: None,
            url: None,
        }
    }
}

