/*
 * Binance Portfolio Margin API
 *
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::pmargin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PmarginCreateListenKeyV1Resp {
    #[serde(rename = "listenKey", skip_serializing_if = "Option::is_none")]
    pub listen_key: Option<String>,
}

impl PmarginCreateListenKeyV1Resp {
    pub fn new() -> PmarginCreateListenKeyV1Resp {
        PmarginCreateListenKeyV1Resp {
            listen_key: None,
        }
    }
}

