/*
 * Binance Portfolio Margin API
 *
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::pmargin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PmarginGetUmApiTradingStatusV1RespIndicators {
    #[serde(rename = "BTCUSDT", skip_serializing_if = "Option::is_none")]
    pub btcusdt: Option<Vec<models::PmarginGetUmApiTradingStatusV1RespIndicatorsBtcusdtInner>>,
}

impl PmarginGetUmApiTradingStatusV1RespIndicators {
    pub fn new() -> PmarginGetUmApiTradingStatusV1RespIndicators {
        PmarginGetUmApiTradingStatusV1RespIndicators {
            btcusdt: None,
        }
    }
}

