/*
 * Binance Portfolio Margin API
 *
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::pmargin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PmarginGetCmOrderAmendmentV1RespItem {
    #[serde(rename = "amendment", skip_serializing_if = "Option::is_none")]
    pub amendment: Option<Box<models::PmarginGetCmOrderAmendmentV1RespItemAmendment>>,
    #[serde(rename = "amendmentId", skip_serializing_if = "Option::is_none")]
    pub amendment_id: Option<i64>,
    #[serde(rename = "clientOrderId", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i64>,
    #[serde(rename = "pair", skip_serializing_if = "Option::is_none")]
    pub pair: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
}

impl PmarginGetCmOrderAmendmentV1RespItem {
    pub fn new() -> PmarginGetCmOrderAmendmentV1RespItem {
        PmarginGetCmOrderAmendmentV1RespItem {
            amendment: None,
            amendment_id: None,
            client_order_id: None,
            order_id: None,
            pair: None,
            symbol: None,
            time: None,
        }
    }
}

