/*
 * Binance Portfolio Margin API
 *
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::pmargin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PmarginGetCmAdlQuantileV1RespItem {
    #[serde(rename = "adlQuantile", skip_serializing_if = "Option::is_none")]
    pub adl_quantile: Option<Box<models::PmarginGetCmAdlQuantileV1RespItemAdlQuantile>>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
}

impl PmarginGetCmAdlQuantileV1RespItem {
    pub fn new() -> PmarginGetCmAdlQuantileV1RespItem {
        PmarginGetCmAdlQuantileV1RespItem {
            adl_quantile: None,
            symbol: None,
        }
    }
}

