/*
 * Binance Portfolio Margin API
 *
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::pmargin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PmarginDeleteCmAllOpenOrdersV1Resp {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
}

impl PmarginDeleteCmAllOpenOrdersV1Resp {
    pub fn new() -> PmarginDeleteCmAllOpenOrdersV1Resp {
        PmarginDeleteCmAllOpenOrdersV1Resp {
            code: None,
            msg: None,
        }
    }
}

