/*
 * Binance Portfolio Margin API
 *
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::pmargin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PmarginGetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner {
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<Vec<models::PmarginGetPortfolioNegativeBalanceExchangeRecordV1RespRowsInnerDetailsInner>>,
    #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<i64>,
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i64>,
}

impl PmarginGetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner {
    pub fn new() -> PmarginGetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner {
        PmarginGetPortfolioNegativeBalanceExchangeRecordV1RespRowsInner {
            details: None,
            end_time: None,
            start_time: None,
        }
    }
}

