/*
 * Binance Portfolio Margin API
 *
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::pmargin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PmarginGetUmAccountV2Resp {
    #[serde(rename = "assets", skip_serializing_if = "Option::is_none")]
    pub assets: Option<Vec<models::PmarginGetCmAccountV1RespAssetsInner>>,
    #[serde(rename = "positions", skip_serializing_if = "Option::is_none")]
    pub positions: Option<Vec<models::PmarginGetUmAccountV2RespPositionsInner>>,
}

impl PmarginGetUmAccountV2Resp {
    pub fn new() -> PmarginGetUmAccountV2Resp {
        PmarginGetUmAccountV2Resp {
            assets: None,
            positions: None,
        }
    }
}

