/*
 * Binance Portfolio Margin API
 *
 * OpenAPI specification for Binance exchange - Pmargin API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::derivatives::pmargin::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PmarginCreateMarginOrderOcoV1Resp {
    #[serde(rename = "contingencyType", skip_serializing_if = "Option::is_none")]
    pub contingency_type: Option<String>,
    #[serde(rename = "listClientOrderId", skip_serializing_if = "Option::is_none")]
    pub list_client_order_id: Option<String>,
    #[serde(rename = "listOrderStatus", skip_serializing_if = "Option::is_none")]
    pub list_order_status: Option<String>,
    #[serde(rename = "listStatusType", skip_serializing_if = "Option::is_none")]
    pub list_status_type: Option<String>,
    #[serde(rename = "marginBuyBorrowAmount", skip_serializing_if = "Option::is_none")]
    pub margin_buy_borrow_amount: Option<String>,
    #[serde(rename = "marginBuyBorrowAsset", skip_serializing_if = "Option::is_none")]
    pub margin_buy_borrow_asset: Option<String>,
    #[serde(rename = "orderListId", skip_serializing_if = "Option::is_none")]
    pub order_list_id: Option<i64>,
    #[serde(rename = "orderReports", skip_serializing_if = "Option::is_none")]
    pub order_reports: Option<Vec<models::PmarginCreateMarginOrderOcoV1RespOrderReportsInner>>,
    #[serde(rename = "orders", skip_serializing_if = "Option::is_none")]
    pub orders: Option<Vec<models::PmarginCreateMarginOrderOcoV1RespOrdersInner>>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "transactionTime", skip_serializing_if = "Option::is_none")]
    pub transaction_time: Option<i64>,
}

impl PmarginCreateMarginOrderOcoV1Resp {
    pub fn new() -> PmarginCreateMarginOrderOcoV1Resp {
        PmarginCreateMarginOrderOcoV1Resp {
            contingency_type: None,
            list_client_order_id: None,
            list_order_status: None,
            list_status_type: None,
            margin_buy_borrow_amount: None,
            margin_buy_borrow_asset: None,
            order_list_id: None,
            order_reports: None,
            orders: None,
            symbol: None,
            transaction_time: None,
        }
    }
}

