/*
 * Binance Wallet API
 *
 * OpenAPI specification for Binance exchange - Wallet API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::wallet::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletCreateBnbBurnV1Resp {
    #[serde(rename = "interestBNBBurn", skip_serializing_if = "Option::is_none")]
    pub interest_bnb_burn: Option<bool>,
    #[serde(rename = "spotBNBBurn", skip_serializing_if = "Option::is_none")]
    pub spot_bnb_burn: Option<bool>,
}

impl WalletCreateBnbBurnV1Resp {
    pub fn new() -> WalletCreateBnbBurnV1Resp {
        WalletCreateBnbBurnV1Resp {
            interest_bnb_burn: None,
            spot_bnb_burn: None,
        }
    }
}

