/*
 * Binance Wallet API
 *
 * OpenAPI specification for Binance exchange - Wallet API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::wallet::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletGetAccountSnapshotV1Resp {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
    #[serde(rename = "snapshotVos", skip_serializing_if = "Option::is_none")]
    pub snapshot_vos: Option<Vec<models::WalletGetAccountSnapshotV1RespSnapshotVosInner>>,
}

impl WalletGetAccountSnapshotV1Resp {
    pub fn new() -> WalletGetAccountSnapshotV1Resp {
        WalletGetAccountSnapshotV1Resp {
            code: None,
            msg: None,
            snapshot_vos: None,
        }
    }
}

