/*
 * Binance Wallet API
 *
 * OpenAPI specification for Binance exchange - Wallet API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::wallet::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletGetAccountApiTradingStatusV1RespDataTriggerCondition {
    #[serde(rename = "GCR", skip_serializing_if = "Option::is_none")]
    pub gcr: Option<i32>,
    #[serde(rename = "IFER", skip_serializing_if = "Option::is_none")]
    pub ifer: Option<i32>,
    #[serde(rename = "UFR", skip_serializing_if = "Option::is_none")]
    pub ufr: Option<i32>,
}

impl WalletGetAccountApiTradingStatusV1RespDataTriggerCondition {
    pub fn new() -> WalletGetAccountApiTradingStatusV1RespDataTriggerCondition {
        WalletGetAccountApiTradingStatusV1RespDataTriggerCondition {
            gcr: None,
            ifer: None,
            ufr: None,
        }
    }
}

